---
title: "624 Trees"
author: "Rebecca Bronstein"
date: "2026-03-30"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rpart)
library(rpart.plot)
library(randomForest)
library(ranger)
library(ipred)
library(gbm)
library(Cubist)
library(C50)
library(caret)

# Load dataset
squirrels <- read.csv("squirrel_fixed.csv")

# Rename columns - replace spaces with dots for easier handling
names(squirrels) <- gsub(" ", ".", names(squirrels))

# Basic cleaning - remove ID columns
squirrels <- squirrels %>%
  select(-X, -Unique.Squirrel.ID) %>%
  drop_na()

# Convert characters to factors
squirrels[] <- lapply(squirrels, function(x) {
  if (is.character(x)) as.factor(x) else x
})

# Train/Test Split
set.seed(123)
train_index <- createDataPartition(squirrels$Primary.Fur.Color, p = 0.7, list = FALSE)
train <- squirrels[train_index, ]
test <- squirrels[-train_index, ]
```

## Classification Tree (Categorical Tree)

```{r classification_tree}
tree_model <- rpart(Primary.Fur.Color ~ ., data = train, method = "class")
plot(tree_model, uniform = TRUE)
text(tree_model, use.n = TRUE, cex = 0.8)

# Predictions
pred_tree <- predict(tree_model, test, type = "class")
confusionMatrix(pred_tree, test$Primary.Fur.Color)
```

## Regression Tree

```{r regression_tree}
reg_tree <- rpart(Y ~ ., data = train, method = "anova")
plot(reg_tree, uniform = TRUE)
text(reg_tree, use.n = TRUE, cex = 0.8)
pred_reg <- predict(reg_tree, test)

# RMSE
sqrt(mean((pred_reg - test$Y)^2))
```

## Rule-Based Tree

```{r rule_model}
rule_model <- C5.0(Primary.Fur.Color ~ ., data = train, rules = TRUE)
summary(rule_model)

pred_rules <- predict(rule_model, test)
confusionMatrix(pred_rules, test$Primary.Fur.Color)
```

## Bagged Trees

```{r bagging}
bag_model <- bagging(Primary.Fur.Color ~ ., data = train, nbagg = 50)
pred_bag <- predict(bag_model, test)
confusionMatrix(pred_bag, test$Primary.Fur.Color)
```
